name: otakunizados
description: "Una app para el mundo otaku."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.1
  url_launcher: ^6.2.3
  table_calendar: ^3.0.9
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Otakunizados.jpg
    - assets/anime.jpg
    - assets/images/logo.png
    - assets/images/dandadan_trailer.jpg