// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz8R4WEyYt2RlSpVQbiDWnLaKNHEvYY_A',
    appId: '1:486636829088:web:161380eb75f5c759be4cc5',
    messagingSenderId: '486636829088',
    projectId: 'otakunizados',
    authDomain: 'otakunizados.firebaseapp.com',
    storageBucket: 'otakunizados.firebasestorage.app',
    measurementId: 'G-PVHXFKLSPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi-K9NNCRqy8anEQ0_IW43jD3xNhyxwaA',
    appId: '1:486636829088:android:99a7bc879118be18be4cc5',
    messagingSenderId: '486636829088',
    projectId: 'otakunizados',
    storageBucket: 'otakunizados.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9NDu1tW0d5ZW-OdoZoldiWoELyY1tVbI',
    appId: '1:486636829088:ios:f714cf6d42c083a7be4cc5',
    messagingSenderId: '486636829088',
    projectId: 'otakunizados',
    storageBucket: 'otakunizados.firebasestorage.app',
    iosBundleId: 'com.example.otakunizados',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9NDu1tW0d5ZW-OdoZoldiWoELyY1tVbI',
    appId: '1:486636829088:ios:f714cf6d42c083a7be4cc5',
    messagingSenderId: '486636829088',
    projectId: 'otakunizados',
    storageBucket: 'otakunizados.firebasestorage.app',
    iosBundleId: 'com.example.otakunizados',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz8R4WEyYt2RlSpVQbiDWnLaKNHEvYY_A',
    appId: '1:486636829088:web:1772c9220ed7ff01be4cc5',
    messagingSenderId: '486636829088',
    projectId: 'otakunizados',
    authDomain: 'otakunizados.firebaseapp.com',
    storageBucket: 'otakunizados.firebasestorage.app',
    measurementId: 'G-1NRGDCGHL7',
  );
}
